### ISSUE TITLE
Ability to turn off slave replication

### ISSUE THREAD

**Issue by twistedgrim** [rackspace-cookbooks/pg-multi#8]
Let us know if we can have a flag to turn off replication.

**Comment by cybermerc** [comment]
@twistedgrim can you provide some additional context about when and how you would want to use this type of flag to help me design something that meets your needs.

**Comment by twistedgrim** [comment]
Just need to be able to flag off the actual replication side of things when we build a slave. 

Build a slave,  have it configured to replicate when needed, then we turn it on manually.

https://github.com/rackspace-cookbooks/pg-multi/blob/master/recipes/_debian_slave.rb#L35-L45

**Comment by cybermerc** [comment]
The new library driven version of this recipe (which will go live within a couple of days) will allow the kind of granular setup your looking to create.
